### ISSUE TITLE
Error 502 - Bad Gateway when user "Hide Email"

### ISSUE THREAD

**Issue by gabriel-ayusso** [aspnet-contrib/AspNet.Security.OAuth.Providers#622]
Hi there, 

I wondering if someone already faced the same issue as me. Sorry if I`m doing something wrong, but I'm getting crazy with this issue.

I implemented Signin with apple on my website and everything is working as expected, but I noticed that in some cases some users are getting 502 - Bad Gateway Error.

After many tests, I noticed that this error happens always when the [Hide my Email](https://support.apple.com/en-us/HT210425) 
 option is checked at login time. I checked the logs, and inspect the network but there is nothing ununsual in the logs.

I double-checked the configuration and everythiing is following the docs. Following you have some configuration. External Login is not even called when the error occurs. 

```csharp
            services.AddAuthentication()
                .AddJwtBearer(IdentityServerConstants.LocalApi.AuthenticationScheme, options =>
                {
                    options.Authority = identityUrl;
                    options.TokenValidationParameters.ValidateIssuer = false;
                    options.TokenValidationParameters.ValidateAudience = false;
                    options.RequireHttpsMetadata = false;
                })
                .AddApple("apple-signin", options =>
                {
                    options.ClientId = "<my_client_id>"; // fixed to test if some configuration are wrong
                    options.KeyId = "<my_key_id>";
                    options.TeamId = "<my_team_id>";
                    options.SaveTokens = true;
                    options.UsePrivateKey((keyId) =>
                    {    
                        var provider = new PhysicalFileProvider(AppContext.BaseDirectory);
                        var contents = provider.GetDirectoryContents(string.Empty);
                        var filePath = $"AuthKey_{keyId}.p8";
                        var fileInfo = provider.GetFileInfo(filePath);
                        return fileInfo;
                    });
                    options.SaveTokens = true;
                });
```

I appreciate any clue!

Bests

**Comment by gabriel-ayusso** [comment]
[SOLVED]

I could catch the error, and it was in nginx configuration.  Nothing with the provider.

The headers of request from Apple when the option `Hide my Email` is on are much bigger than the usual, so it breaks on nginx. I can see the following message on the controller logs

`[error] 497#497: *35459617 upstream sent too big header while reading response header from upstream`

And I'm also using kubernetes. For the ones who getting the same issue as me, I fixed the issue putting the following annotation on my ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alien-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "1m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "1m"
spec:
#next rows ommited for readability
```

Thank you so much!
