### ISSUE TITLE
GitHub Oauth Callback does not work with Reverse Proxy

### ISSUE THREAD

**Issue by KaiDevrim** [aspnet-contrib/AspNet.Security.OAuth.Providers#700]
### GitHub

I am currently trying to host a web app that uses this library for GitHub Oauth support. The reverse proxy I am using, lsio/swag does not seem to work with the callback that the examples give. My current oauth setup is just like in the example MVC.Client and my current nginx config for this is like so:
```
location / {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /ldaplogin;

    # enable for Authelia, also enable authelia-server.conf in the default site config
    #include /config/nginx/authelia-location.conf;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app star;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

I deployed the app in docker like so:
```
version: '2'

services:
  star:
    build:
      context: /home/opc/StarItAllWeb
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "4430:443"

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=dvr.im
      - SUBDOMAINS=star,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./data:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
```
